#!/usr/bin/env python3
"""wiki.py — keep the wiki graph honest.

The plan predicted this failure: "double-linking will rot in a week. Models skip
the boring write. After three matches, Linked from blocks and INDEX.md are lies."

So backlinks are not the agent's job. They are computed from the real graph.
The agent writes `Links out`. This script derives every `Linked from` block and
regenerates INDEX.md from what the files actually say.

Commands:
  check      report broken links, ambiguous slugs, missing blocks. Exit 1 on error.
  backlinks  rewrite every `## Linked from` block from the real graph.
  index      regenerate wiki/INDEX.md with true inbound counts.
  sync       backlinks + index, then check.

Only stdlib. Python 3.8+.
"""

import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIKI = os.path.join(ROOT, "wiki")

# One canonical page per idea. Break point 4: the same rule was forked into two
# folders, so `[[taking-space]]` had no defined target. These win. Every other
# page carrying the same basename is treated as a stub that points here.
CANONICAL = {
    "taking-space": "doctrine/taking-space.md",
    "rest-defence": "doctrine/rest-defence.md",
    "PROTOCOL": "trainer/PROTOCOL.md",
    "starting-position": "positional/goalie/starting-position.md",
    "come-off-the-line": "positional/goalie/come-off-the-line.md",
    "in-possession": "head-coach/in-possession.md",
    "out-of-possession": "head-coach/out-of-possession.md",
    "transitions": "head-coach/transitions.md",
}

# Hub pages whose basename is INDEX. `[[positional]]` should reach the hub, so
# expose directory-named aliases instead of seven pages all called INDEX.
DIR_ALIAS = {
    "analysis/INDEX.md": "analysis",
    "head-coach/INDEX.md": "head-coach",
    "positional/INDEX.md": "positional",
    "pro/INDEX.md": "pro",
    "trainer/INDEX.md": "trainer",
    "noop/INDEX.md": "noop",
    "INDEX.md": "wiki",
}

GENERATED = "<!-- generated by scripts/wiki.py. Do not hand-edit below. -->"

FENCE = re.compile(r"```.*?```", re.S)
INLINE = re.compile(r"`[^`\n]*`")
WIKILINK = re.compile(r"\[\[([^\]|]+)(?:\|[^\]]*)?\]\]")


def pages():
    out = {}
    for base, dirs, files in os.walk(WIKI):
        dirs[:] = [d for d in dirs if d not in ("frames",)]
        for f in sorted(files):
            if f.endswith(".md"):
                p = os.path.join(base, f)
                rel = os.path.relpath(p, WIKI)
                with open(p, encoding="utf-8") as fh:
                    out[rel] = fh.read()
    return out


def prose(text):
    """Strip fenced and inline code. Template placeholders like [[match-slug]]
    live inside fences and are examples, not real links."""
    return INLINE.sub("", FENCE.sub("", text))


def slug_of(rel):
    return os.path.splitext(os.path.basename(rel))[0]


def is_template(rel):
    """Files starting with _ are skeletons to copy, not nodes in the graph.
    They are exempt from link rules."""
    return os.path.basename(rel).startswith("_")


def is_stub(text):
    return "Canonical page:" in text.split("## Links out")[0]


def build(docs):
    """slug -> single target page. Canonical map wins, then non-stubs."""
    by_slug = defaultdict(list)
    for rel, txt in docs.items():
        by_slug[slug_of(rel)].append(rel)
    for rel, alias in DIR_ALIAS.items():
        if rel in docs:
            by_slug[alias].append(rel)

    resolve, ambiguous = {}, {}
    for slug, rels in by_slug.items():
        if slug in CANONICAL and CANONICAL[slug] in docs:
            resolve[slug] = CANONICAL[slug]
            continue
        if len(rels) == 1:
            resolve[slug] = rels[0]
            continue
        real = [r for r in rels if not is_stub(docs[r])]
        if len(real) == 1:
            resolve[slug] = real[0]
        else:
            ambiguous[slug] = rels
    return resolve, ambiguous


def links(docs, resolve):
    """page -> set of pages it points at. Plus unresolved slugs and every slug
    actually referenced (so ambiguity is only an error if someone links it)."""
    out = defaultdict(set)
    broken = defaultdict(set)
    referenced = set()
    for rel, txt in docs.items():
        body = prose(txt)
        # Only count links ABOVE the generated backlink block, so backlinks
        # never feed themselves.
        body = body.split(GENERATED)[0]
        for m in WIKILINK.findall(body):
            slug = m.strip()
            referenced.add(slug)
            tgt = resolve.get(slug)
            if tgt is None:
                broken[rel].add(slug)
            elif tgt != rel:
                out[rel].add(tgt)
    return out, broken, referenced


def inbound_map(outmap):
    inb = defaultdict(set)
    for src, tgts in outmap.items():
        for t in tgts:
            inb[t].add(src)
    return inb


def label(rel):
    s = slug_of(rel)
    return DIR_ALIAS.get(rel, s)


def write_backlinks(docs, inb):
    """Replace each page's `## Linked from` body with the computed graph."""
    changed = []
    for rel, txt in sorted(docs.items()):
        if rel == "INDEX.md" or is_template(rel):
            continue
        if "## Linked from" not in txt:
            continue

        head, _, _tail = txt.partition("## Linked from")
        srcs = sorted(inb.get(rel, ()), key=lambda r: (label(r).lower(), r))

        lines = ["## Linked from", "", GENERATED, ""]
        if srcs:
            for s in srcs:
                depth = rel.count(os.sep)
                back = "../" * depth
                lines.append(f"- [{label(s)}]({back}{s}) (`{label(s)}`)")
        else:
            lines.append("_Nothing links here yet._")
        lines.append("")

        new = head.rstrip() + "\n\n" + "\n".join(lines)
        if new != txt:
            with open(os.path.join(WIKI, rel), "w", encoding="utf-8") as fh:
                fh.write(new)
            changed.append(rel)
    return changed


def page_type(rel):
    top = rel.split(os.sep)[0]
    known = {
        "doctrine", "team", "analysis", "noop",
        "trainer", "positional", "head-coach", "pro",
    }
    return top if top in known else "root"


def write_index(docs, outmap, inb):
    rows = []
    for rel in sorted(docs):
        if rel == "INDEX.md":
            continue
        rows.append((
            rel,
            page_type(rel),
            len(inb.get(rel, ())),
            len(outmap.get(rel, ())),
        ))

    orphans = [r for r, _t, i, _o in rows
               if i == 0 and not is_template(r) and not r.endswith("INDEX.md")]

    lines = [
        "# Wiki index",
        "",
        "Generated by `scripts/wiki.py index`. Do not hand-edit.",
        "",
        "Inbound and outbound are counted from real `[[links]]` in the files, not",
        "from what a page claims. If a number here looks wrong, the links are wrong.",
        "",
        "## Canonical slugs",
        "",
        "One page per idea. Every other path with the same name is a stub that points here.",
        "",
        "| Slug | Canonical page |",
        "|---|---|",
    ]
    for slug in sorted(CANONICAL):
        tgt = CANONICAL[slug]
        if tgt in docs:
            lines.append(f"| `{slug}` | [{tgt}]({tgt}) |")

    lines += [
        "",
        "## Pages",
        "",
        "| Page | Type | Inbound | Outbound |",
        "|---|---|---|---|",
    ]
    for rel, typ, i, o in rows:
        lines.append(f"| [{rel}]({rel}) | {typ} | {i} | {o} |")

    lines += [
        "",
        "## Orphans",
        "",
        "Nothing links to these. Either link them from a hub or delete them.",
        "A page that cannot earn two inbound links should be a bullet on a hub,",
        "not a page.",
        "",
    ]
    lines += [f"- [{r}]({r})" for r in orphans] or ["_None._"]

    lines += [
        "",
        "## Working memory",
        "",
        "TEAM, STRENGTHS, GAPS, KEEPER, THIS-WEEK, and the last 5 match pages.",
        "LEARNINGS is archive. Never load all doctrine. Never load CANDIDATES into",
        "a coaching pass.",
        "",
    ]

    with open(os.path.join(WIKI, "INDEX.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return len(rows), orphans


def check(docs, resolve, ambiguous, outmap, broken, referenced):
    errs, warns = [], []

    for rel in sorted(broken):
        for slug in sorted(broken[rel]):
            errs.append(f"{rel}: [[{slug}]] points at no page")

    for slug, rels in sorted(ambiguous.items()):
        # Only a problem if something actually links the slug. Seven pages named
        # INDEX.md is fine as long as nobody writes [[INDEX]].
        if slug not in referenced:
            continue
        errs.append(
            f"[[{slug}]] is ambiguous across {rels}. "
            f"Add it to CANONICAL in scripts/wiki.py, or make the extras stubs."
        )

    for rel, txt in sorted(docs.items()):
        if rel == "INDEX.md" or is_template(rel):
            continue
        if "## Links out" not in txt:
            errs.append(f"{rel}: missing '## Links out'")
        if "## Linked from" not in txt:
            errs.append(f"{rel}: missing '## Linked from'")

    inb = inbound_map(outmap)
    for rel in sorted(docs):
        if is_template(rel) or rel.endswith("INDEX.md"):
            continue
        # Stubs are supposed to be orphans. They exist so a reader who lands on
        # the wrong path gets redirected. Links resolve to the canonical page.
        if is_stub(docs[rel]):
            continue
        if not inb.get(rel):
            warns.append(f"{rel}: orphan, nothing links here")
        if not outmap.get(rel):
            warns.append(f"{rel}: links out to nothing")

    return errs, warns


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    if not os.path.isdir(WIKI):
        print(f"no wiki/ at {WIKI}", file=sys.stderr)
        return 2

    docs = pages()
    resolve, ambiguous = build(docs)
    outmap, broken, referenced = links(docs, resolve)
    inb = inbound_map(outmap)

    if cmd in ("backlinks", "sync"):
        changed = write_backlinks(docs, inb)
        print(f"backlinks: rewrote {len(changed)} page(s)")
        docs = pages()
        resolve, ambiguous = build(docs)
        outmap, broken, referenced = links(docs, resolve)
        inb = inbound_map(outmap)

    if cmd in ("index", "sync"):
        n, orphans = write_index(docs, outmap, inb)
        print(f"index: {n} pages, {len(orphans)} orphan(s)")

    if cmd in ("check", "sync"):
        errs, warns = check(docs, resolve, ambiguous, outmap, broken, referenced)
        for w in warns:
            print(f"warn:  {w}")
        for e in errs:
            print(f"ERROR: {e}")
        print(f"\n{len(docs)} pages, {len(errs)} error(s), {len(warns)} warning(s)")
        if errs:
            return 1

    if cmd not in ("check", "backlinks", "index", "sync"):
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
